name: PR Approval

on:
  pull_request:
    branches:
      - maain
    types:
      - opened

jobs:
  build:
    name: Auto-approve
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'softwarepete'

    steps:
      - name: Auto-approve PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            });
            console.log(result.status);
