name: PR Approval

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened

jobs:
  build:
    name: Auto-approve
    runs-on: ubuntu-latest

    steps:
      - name: Check PR owner and status
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            if (response.data.user.login === 'softwarepete' && response.data.state === 'open') {
              const result = await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: "APPROVE"
              });
              console.log(result.status);
            }
